#version: '3.1'
#
#services:
#  db:
#    image: postgres
#    ports:
#      - "5555:5432"
#    restart: always
#    environment:
#      POSTGRES_USER: bookit
#      POSTGRES_PASSWORD: difficult_password

version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5723:5432"
    restart: always
    environment:
      POSTGRES_USER: bookit
      POSTGRES_PASSWORD: difficult_password



#version: '3.8'
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8096:8080"
#    container_name: "bookit_app"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookit_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#
#  db:
#    image: postgres:15
#    container_name: postgres-container
#    ports:
#      - "4936:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: bookit_db
