version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: bookit
      POSTGRES_PASSWORD: difficult_password
      POSTGRES_DB: bookit


