spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: bookit
    password: difficult_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret_key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration_time: 60000      # 1000 * 60 * 10 ms (10 minutes)